const songReviews = {
    '4kWO6O1BUXcZmaxitpVUwp': { 'name': 'Jackie Chan', 'review': 'Absolute JAM. First song on my playlist for the past 4 months...' },
    '0ljz8e0tQT3piSlT6tKWAV': { 'name': 'Prelude', 'review': 'Simple. Great. Beats.' },
    '3PTMcrpi5tbHzc8xxOZ8lG': { 'name': 'Nothing On Us', 'review': 'You got nothin on me' },
    '1PBk2knn4anq0vaS5KGDG2': { 'name': 'In My Head', 'review': 'Gets you ready to run through a wall' },
    '1nas007nDbzLwDGwvMdz79': { 'name': 'How You Love Me', 'review': 'Get the people goin' },
    '3huV7eiNpaQlCB3LbZi9bB': { 'name': 'Bad Habit', 'review': 'The Kooks get me goin!' },
    '2NFWA9nqzDh4glNiNp1Stc': { 'name': 'Pressure - Alesso Remix', 'review': '"Oldie" but a goodie' },
    '46lFttIf5hnUZMGvjK0Wxo': { 'name': 'Runaway (U & I)', 'review': 'It\'s topical' },
    '12GEpg2XOPyqk03JZEZnJs': { 'name': 'It Ain’t Me (with Selena Gomez)', 'review': 'This song will always be great to run to' },
    '64dkTKKNLwbjBuU4xnS2ei': { 'name': 'Games Continued - Radio Edit', 'review': '' },
    '24LS4lQShWyixJ0ZrJXfJ5': { 'name': 'Sweet Nothing (feat. Florence Welch)', 'review': '' },
    '0LIU3eOAwXCZlWOiHuItkj': { 'name': 'Help Our Souls (Urban Contact Radio Edit)', 'review': 'Classic  techno jam' },
    '3Vf9mxFMad7VR3G10QZwia': { 'name': 'Free (feat. Emeli Sandé) - Cash Cash x Gazzo Remix', 'review': '' },
    '4XLm8FNvaTlmTAZmSrrV82': { 'name': 'Shots - Broiler Remix', 'review': '' },
    '2Kl1E3NdbzT7vVi93TffoX': { 'name': 'Pompeii - Audien Remix', 'review': '' },
    '57rhFcwEY1MTo3jx2af8Qk': { 'name': 'Make Me Feel', 'review': '' },
    '3uJsg8xIH7OpWHxuJaMLJX': { 'name': 'Ride Or Die (feat. Foster The People)', 'review': 'Just great vibes' },
    '1cdezJ6rwD2wG3kza3MWvK': { 'name': 'Green Light (feat. Morgan St. Jean)', 'review': '' },
    '06h3McKzmxS8Bx58USHiMq': { 'name': 'Silhouettes - Original Radio Edit', 'review': 'Take me back to highschool senior year... RIP Avicii' },
    '2j7HtVwC0DUoQqHSKDKTPz': { 'name': 'Fix You', 'review': '' },
    '3s4U7OHV7gnj42VV72eSZ6': { 'name': 'Rather Be (feat. Jess Glynne)', 'review': '' },
    '0kLH6LddJmVAlLM37zNqxf': { 'name': 'Sweet Melodies (Schier Remix)', 'review': 'Jam alert' },
    '4dvkDDMC5LVvD437YaxOA2': { 'name': 'What I Love', 'review': 'I got I got what you want' },
    '6YUTL4dYpB9xZO5qExPf05': { 'name': 'Summer', 'review': 'This got me way more jacked up when it was warm outside' },
    '3jKK86aBY7Uxn4fmtSOVfk': { 'name': 'Turn It Down (with Rebecca & Fiona) - Radio Edit', 'review': '' },
    '6RnkFd8Fqqgk1Uni8RgqCQ': { 'name': 'Like I Do', 'review': 'Davy G is pretty intense' },
    '4cxvludVmQxryrnx1m9FqL': { 'name': 'My Shot', 'review': 'This is not a moment, it\'s the Movement!' },
    '4SoXQCrPQplashFebNaUw3': { 'name': 'Get It Right', 'review': '' },
    '6FeAfj1h12aakG9KqK7u3u': { 'name': 'It Was London', 'review': 'Need more Kooks' },
    '6ZXO2ZFcAFmkFoJpMIwzGa': { 'name': 'Goin Up', 'review': '' },
    '3Q95VQL8yWRO8mkF6VoDzi': { 'name': 'Sunset Jesus', 'review': 'RIP my dude' },
    '7MkAPNqXIBgdfCqaQJDEOM': { 'name': 'Kamikaze - Urban Contact Remix', 'review': '' },
    '6EsH66Uto1zwZlDGQ6RokU': { 'name': 'Forbidden Voices', 'review': '' },
    '447yWcDPg1ddgcHBLGpJC0': { 'name': 'Better Not (feat. Wafia)', 'review': '' },
    '22qUyTlEvJf6DAlyQjMADe': { 'name': 'Leaving You', 'review': 'Sad words, great beat' },
    '5ojylAKdFKpkw9axHNruKG': { 'name': 'Love', 'review': '' },
    '5miQGFoYZPv5JCNzSoEbWt': { 'name': 'Know This Love (feat. Litens)', 'review': '' },
    '6ReKt5x6FVUXTMdWNC6GAQ': { 'name': 'Lotus Eater', 'review': 'One of my favorites of the past year, solid jam' },
    '2HuSaKSnkvSaRQviRm1glh': { 'name': 'Ride Or Die (feat. Foster The People) - Vicetone Remix', 'review': 'Only song on this playlist 2x, remix is a jam' },
    '57QXXEBy5apjgxsyXSb8YE': { 'name': 'Satisfied (feat. MAX)', 'review': 'Galantis is amazing for running' },
    '63Qco1ncI5U4qEUnxL1DsH': { 'name': 'Living', 'review': '' },
    '05bUAkDRK3xzvVkZlGU6ee': { 'name': 'Inhale', 'review': '' },
    '2Yo4fEPlHTxTpvo05bAb04': { 'name': 'On Your Way Down', 'review': 'It\s too bad these guys live in New Zealand' },
    '2aOlxywgl4nCD4Xh2mLWM7': { 'name': 'Spaceship (feat. Uffie)', 'review': '' },
    '0XLRWENZmLC02r36ne7GiS': { 'name': 'Another Dimension - Miike Snow Remix', 'review': '' },
    '5kgqTe1BM720OjU78TGYDw': { 'name': 'Tell Me You Love Me', 'review': '' },
    '7412fpVfB2PSSb1nENQczC': { 'name': 'Sheep', 'review': 'A little slow to run to, but this is my favorite song' },
    '77oPBfV05yqQHGaq31OxFS': { 'name': 'Alona', 'review': 'A little slow... but parts of this song are too good' },
    '2GoLbyGzBYqDBq65hWs5ml': { 'name': 'Alone - CID Remix', 'review': '' },
    '3rYfOYJb6I21qt8aX3hs2P': { 'name': 'Mela', 'review': 'Don\'t know the words know the beats' },
    '6tB4XVKceo2307SSWXaO0y': { 'name': 'Just Friends', 'review': '' },
    '5PsLICW9HfBbHZ64TT1liT': { 'name': 'Future Pt 2', 'review': '' },
    '7EqpEBPOohgk7NnKvBGFWo': { 'name': 'Wait For It', 'review': '' },
    '6luLsRZ41am7UwwQq7rEzJ': { 'name': 'Where Do We Go from Here', 'review': '' },
    '1RNybormZ5O0s3DCIRQWq4': { 'name': 'Bright Blue Day Haze', 'review': '' },
    '739wgqW608GZoyfLHFLsPy': { 'name': 'Leave It In My Dreams', 'review': 'The Voidz are a funky band, but this song rocks' },
    '7jFuj6FV32pOgf0WU9t6bM': { 'name': 'King - Basic Tape Remix', 'review': '' },
    '2MTSo2SGQ0oVKgPu99x3Df': { 'name': 'Dopamine', 'review': 'Bursting at the seems of Dopamine' }
};

export { songReviews };