const songReviews = {
    '4kWO6O1BUXcZmaxitpVUwp': { 'name': 'Jackie Chan', 'review': 'Absolute JAM. First song on my playlist for the past 4 months...' },
    '0ljz8e0tQT3piSlT6tKWAV': { 'name': 'Prelude', 'review': 'Simple. Great. Beats.' },
    '3PTMcrpi5tbHzc8xxOZ8lG': { 'name': 'Nothing On Us', 'review': 'You got nothin on me.' },
    '1PBk2knn4anq0vaS5KGDG2': { 'name': 'In My Head', 'review': 'Recommend listening to this song if you\'re preparing to run through a wall.' },
    '1nas007nDbzLwDGwvMdz79': { 'name': 'How You Love Me', 'review': 'Another ideal workout/running song.' },
    '3huV7eiNpaQlCB3LbZi9bB': { 'name': 'Bad Habit', 'review': 'The Kooks, and this song, just get me feelin bad!' },
    '2NFWA9nqzDh4glNiNp1Stc': { 'name': 'Pressure - Alesso Remix', 'review': '"Oldie" but a goodie.' },
    '46lFttIf5hnUZMGvjK0Wxo': { 'name': 'Runaway (U & I)', 'review': 'It\'s topical (RUN).' },
    '12GEpg2XOPyqk03JZEZnJs': { 'name': 'It Ain’t Me (with Selena Gomez)', 'review': 'Always is and always will be giving out great vibes.' },
    '64dkTKKNLwbjBuU4xnS2ei': { 'name': 'Games Continued - Radio Edit', 'review': 'Princeton Lax pregame strech beats 2017.' },
    '24LS4lQShWyixJ0ZrJXfJ5': { 'name': 'Sweet Nothing (feat. Florence Welch)', 'review': 'Calvin Harris never goes out of style.' },
    '0LIU3eOAwXCZlWOiHuItkj': { 'name': 'Help Our Souls (Urban Contact Radio Edit)', 'review': 'Very smooth, classic techno jam.' },
    '3Vf9mxFMad7VR3G10QZwia': { 'name': 'Free (feat. Emeli Sandé) - Cash Cash x Gazzo Remix', 'review': 'Reminds me of losing my mind freshman year 2014.' },
    '4XLm8FNvaTlmTAZmSrrV82': { 'name': 'Shots - Broiler Remix', 'review': 'Insirpation, in song form.' },
    '2Kl1E3NdbzT7vVi93TffoX': { 'name': 'Pompeii - Audien Remix', 'review': 'Talk about a fire remix! (Volcano joke)' },
    '57rhFcwEY1MTo3jx2af8Qk': { 'name': 'Make Me Feel', 'review': 'Make me feel love!!' },
    '3uJsg8xIH7OpWHxuJaMLJX': { 'name': 'Ride Or Die (feat. Foster The People)', 'review': 'Just great vibes, top 5 song of the last few months.' },
    '1cdezJ6rwD2wG3kza3MWvK': { 'name': 'Green Light (feat. Morgan St. Jean)', 'review': 'Alright, it\'s a little girly, but it\'s great.' },
    '06h3McKzmxS8Bx58USHiMq': { 'name': 'Silhouettes - Original Radio Edit', 'review': 'Highschool senior year... RIP Avicii' },
    '2j7HtVwC0DUoQqHSKDKTPz': { 'name': 'Fix You', 'review': 'Da da da da-da da da daaaaaa da da da-da da.' },
    '3s4U7OHV7gnj42VV72eSZ6': { 'name': 'Rather Be (feat. Jess Glynne)', 'review': 'I feel like I\'m right where I want to be. Especially if I\'m listening to this song.' },
    '0kLH6LddJmVAlLM37zNqxf': { 'name': 'Sweet Melodies (Schier Remix)', 'review': 'Jam alert! Uh oh!' },
    '4dvkDDMC5LVvD437YaxOA2': { 'name': 'What I Love', 'review': 'I got I got what you want.' },
    '6YUTL4dYpB9xZO5qExPf05': { 'name': 'Summer', 'review': 'This got me way more jacked up when it was warm outside' },
    '3jKK86aBY7Uxn4fmtSOVfk': { 'name': 'Turn It Down (with Rebecca & Fiona) - Radio Edit', 'review': 'Take about throwback beats.' },
    '6RnkFd8Fqqgk1Uni8RgqCQ': { 'name': 'Like I Do', 'review': 'David G is pretty intense.' },
    '4cxvludVmQxryrnx1m9FqL': { 'name': 'My Shot', 'review': 'This is not a moment, it\'s The Movement!' },
    '4SoXQCrPQplashFebNaUw3': { 'name': 'Get It Right', 'review': 'I heard this song on a peleton class once.' },
    '6FeAfj1h12aakG9KqK7u3u': { 'name': 'It Was London', 'review': 'Need more Kooks' },
    '6ZXO2ZFcAFmkFoJpMIwzGa': { 'name': 'Goin Up', 'review': 'I don\'t understand the squeaky techno voice trend.' },
    '3Q95VQL8yWRO8mkF6VoDzi': { 'name': 'Sunset Jesus', 'review': 'This one goes out to Sunset Jesus, RIP my dude.' },
    '7MkAPNqXIBgdfCqaQJDEOM': { 'name': 'Kamikaze - Urban Contact Remix', 'review': 'Urban Contact, whoever these guys are, just get it.' },
    '6EsH66Uto1zwZlDGQ6RokU': { 'name': 'Forbidden Voices', 'review': 'Random, loud, harmonious screaming.' },
    '447yWcDPg1ddgcHBLGpJC0': { 'name': 'Better Not (feat. Wafia)', 'review': 'I listened to this song on repeat for a week or two.' },
    '22qUyTlEvJf6DAlyQjMADe': { 'name': 'Leaving You', 'review': 'Sad, sad lyrics, great beat.' },
    '5ojylAKdFKpkw9axHNruKG': { 'name': 'Love', 'review': 'It\'s hard not to move with this song.' },
    '5miQGFoYZPv5JCNzSoEbWt': { 'name': 'Know This Love (feat. Litens)', 'review': 'This song has ups and downs, but overall made the playlist.' },
    '6ReKt5x6FVUXTMdWNC6GAQ': { 'name': 'Lotus Eater', 'review': 'One of my favorites of the past year, solid rock jam.' },
    '2HuSaKSnkvSaRQviRm1glh': { 'name': 'Ride Or Die (feat. Foster The People) - Vicetone Remix', 'review': 'Only song on this playlist 2x, the remix is too good.' },
    '57QXXEBy5apjgxsyXSb8YE': { 'name': 'Satisfied (feat. MAX)', 'review': 'Galantis is made for workingout.' },
    '63Qco1ncI5U4qEUnxL1DsH': { 'name': 'Living', 'review': 'Check out this song at 0:50, I mean comon!' },
    '05bUAkDRK3xzvVkZlGU6ee': { 'name': 'Inhale', 'review': 'Filler beats honestly.' },
    '2Yo4fEPlHTxTpvo05bAb04': { 'name': 'On Your Way Down', 'review': 'It\'s really too bad these guys are from in New Zealand.' },
    '2aOlxywgl4nCD4Xh2mLWM7': { 'name': 'Spaceship (feat. Uffie)', 'review': 'The most repetitive song on this playlist by a mile... but don\'t hate it.' },
    '0XLRWENZmLC02r36ne7GiS': { 'name': 'Another Dimension - Miike Snow Remix', 'review': 'Just when you think it\'s over, it keeps comin.' },
    '5kgqTe1BM720OjU78TGYDw': { 'name': 'Tell Me You Love Me', 'review': 'Honestly just threw on all of Galantis\'s new songs' },
    '7412fpVfB2PSSb1nENQczC': { 'name': 'Sheep', 'review': 'A little slow to run to, but this is my favorite song hands down.' },
    '77oPBfV05yqQHGaq31OxFS': { 'name': 'Alona', 'review': 'A little slow... but imagine if I get to run over the Queensboro bridge at 0:44.' },
    '2GoLbyGzBYqDBq65hWs5ml': { 'name': 'Alone - CID Remix', 'review': 'There is a shockinig lack of airhorn in this playlist. Check out the drop at 1:08.' },
    '3rYfOYJb6I21qt8aX3hs2P': { 'name': 'Mela', 'review': 'Don\'t know the words know the beats.' },
    '6tB4XVKceo2307SSWXaO0y': { 'name': 'Just Friends', 'review': 'Just fwends.' },
    '5PsLICW9HfBbHZ64TT1liT': { 'name': 'Future Pt 2', 'review': 'I shazamed this song on a party bus.' },
    '7EqpEBPOohgk7NnKvBGFWo': { 'name': 'Wait For It', 'review': 'Don\'t knock it. Listen to the words.' },
    '6luLsRZ41am7UwwQq7rEzJ': { 'name': 'Where Do We Go from Here', 'review': 'The chord progression in this song is my favorite kind of music (1:05).' },
    '1RNybormZ5O0s3DCIRQWq4': { 'name': 'Bright Blue Day Haze', 'review': 'Yup yup that\'ll do it. Great guitar.' },
    '739wgqW608GZoyfLHFLsPy': { 'name': 'Leave It In My Dreams', 'review': 'The Voidz are a funky band, but this song textbook groovy!' },
    '7jFuj6FV32pOgf0WU9t6bM': { 'name': 'King - Basic Tape Remix', 'review': 'I thought the lyrics were "treat you like a kid" for a very long time.' },
    '2MTSo2SGQ0oVKgPu99x3Df': { 'name': 'Dopamine', 'review': 'Bursting at the seams with dopamine. ' }
};

export { songReviews };